name: macman
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.36.2
  modal_bottom_sheet: ^2.0.0
  select_form_field: "^2.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets: 
    - img/

  fonts:
  - family: AquawaxPro
    fonts:
    - asset: AquawaxPro/AquawaxPro-Regular.otf
    - asset: AquawaxPro/AquawaxPro-Bold.otf
    - asset: AquawaxPro/AquawaxPro-Light.otf
    - asset: AquawaxPro/AquawaxPro-UltraBold.otf
    - asset: AquawaxPro/AquawaxPro-DemiBold.otf
    - asset: AquawaxPro/AquawaxPro-Medium.otf
    
    
    